### ISSUE TITLE
Update welcome pane text

### ISSUE THREAD

**Issue by lparsons** [PrincetonUniversity/neuron-graph#102]
Dr. Leifer continues to worry about readers and reviewers panicking because they do not realize that we are only showing `q<0.05` connections. The text was updated to further stress that additional connections are visible in the paper.

Some new updates for the welcome pane text: https://docs.google.com/document/d/1mFf4RLW8QvE5DItCLo04klDnfJ2LQC_i6RUzVpOFwVs/edit?usp=sharing

**Comment by aleifer** [comment]
OK. Sorry. Based on additional feedback from Francesco I have now changed the bolded  text one more time. Sorry. Could you please update the bolded text again? Thanks!

**Comment by aleifer** [comment]
OK. Sorry. Based on additional feedback from Francesco I have now changed the bolded text one more time. Sorry. Could you please update the bolded text again? Thanks!
