### ISSUE TITLE
Add functional connections data to "complete animal" in addition to "head ganglia" dataset category

### ISSUE THREAD

**Issue by lparsons** [PrincetonUniversity/neuron-graph#105]
**Feature Inspiration**

Currently our functional dataset includes neurons that are missing from the “head ganglia”  anatomical datasets. Conversely our functional dataset lacks many neurons that are included in the “complete animal”  anatomical datasets.

As a result, some neurons that are highlighted in the paper (*e.g.* M3, MI, ML, I3 and I4) are missing. Searches for those neurons result in no data being displayed and the message "<neuron> is not in the head datasets."
![image](https://user-images.githubusercontent.com/645128/182934768-48d43b3a-a6e1-4326-802e-b8204af94b1d.png)

**Feature Description**

The best solution that we can come up with would be to create two copies of our functional dataset, one that would be listed in “head ganglia” and another identical copy that would be listed in the “complete animal” categories.

The user would experience two behaviors:

1. When looking at “head ganglia” category, there will be instances where functional connections are omitted. Here we suggest updating the “missing” error message to say something like: “This neuron is not included in the head dataset. Please select complete animal to view this neuron.”
2. When looking at “complete animal” category all of our functional connections will be included, but if the user looks at anatomy they will see anatomical connections for which we have no functional data.

* [ ] duplicate the existing WT dataset
* [ ] tag the copy as a "complete animal" dataset
* [ ] add the copy to the database
* [ ] updating the message for neurons not in the head dataset
* [ ] re-categorize the unc-31 data as "complete animal" so that all neurons can be displayed

**Alternatives Considered**

**Comment**

**Comment by aleifer** [comment]
Hi, looking at this, I think the unc-31 data should also appear in both catagories, just like the WT dataset. So it should also be duplicated.

**Comment by lparsons** [comment]
> Hi, looking at this, I think the unc-31 data should also appear in both catagories, just like the WT dataset. So it should also be duplicated.

That's not how the unc-31 data works though. It is it's own separate category. We can "re-categorize" it as "complete animal" though so that nothing is hidden when you view it.

**Comment by aleifer** [comment]
oh. ok. yes. that makes sense. thank you.
