### ISSUE TITLE
Replace "Tour" with "Welcome" pane

### ISSUE THREAD

**Issue by lparsons** [PrincetonUniversity/neuron-graph#59]
**Feature Inspiration**

When a user first goes to the website there is no introduction about what the site is and what type of data can be found there. It woudl be nice to get a quick overview of what the website provides.

**Feature Description**

Turn off the automatic "tour" panes and instead have a single "Welcome page" popup. Contents:

---
## FunCoNN (Beta)
 
Welcome to FuNCoNN (Beta): Functional Connectivity on NemaNode
 
This is an interactive browser of functional connectivity measurements of _C. elegans_ overlaid on select connectomics data using the [NemaNode](https://nemanode.org/) software.  
 
Functional connectivity measurements show the casual direction of information flow, polarity and functional strength of neural connections based on optogenetic perturbations and calcium imaging. Functional measurements shown in this visualization are from a forthcoming manuscript from the [Leifer Lab](http://leiferlab.princeton.edu/): Randi, Dvali, Sharma and Leifer, “Direct Measurements of Functional Connectivity,” in prep.   Only those measured connections with a q-value less than 0.05 are shown.
 
Measurements are displayed using [NemaNode](https://nemanode.org/), an open source [software package](https://github.com/zhenlab-ltri/NemaNode) described in [Witvleit et al., 2021](https://doi.org/10.1038/s41586-021-03778-8) from the Zhen, Samuel and Licthman labs. Select connectomics datasets from Witvleit et al, and others are also displayed.
 
This project is in beta and has not yet been peer reviewed.
 
Data and code are released under a permissive license at [https://github.com/PrincetonUniversity/neuron-graph/](https://github.com/PrincetonUniversity/neuron-graph/)

---

**Alternatives Considered**

**Comment**

**Comment by bdsinger** [comment]
almost done, just an issue getting it to go away (see pr 86 https://github.com/PrincetonUniversity/neuron-graph/pull/86 )

**Comment by lparsons** [comment]
Closed by #86
