### ISSUE TITLE
Bad legend display in Firefox browser

### ISSUE THREAD

**Issue by hepcat72** [PrincetonUniversity/neuron-graph#64]
**Problem**

Hidden/missing icon references display something in Firefox whereas they display nothing in other browsers

**Steps to reproduce**

1. Go to the website in Firefox

**Current behavior**

<img width="178" alt="funconn_firefox_weirdity" src="https://user-images.githubusercontent.com/2300532/178791863-46818d28-810b-41fa-aa11-ac6fa622c076.png">

**Expected behavior**

<img width="178" alt="legend_appearance" src="https://user-images.githubusercontent.com/2300532/178794752-4058f273-b2d9-4240-b5c1-f39e1db3db67.png">

**Suggested Change**

The css defines images to display using some sort of mapping and I recall that when the image(/mapping?) didn't exist (in other browsers) there was no image displayed, but the spacing lined up correctly.  Either the spacing should be set using CSS or a transparent image should be mapped.

**Comment**

none

**Comment by lparsons** [comment]
@hepcat72 We need to bump the priority of this issue. It would be great to get it fixed before the paper gets published on Arxiv (likely Thurs, 7/28)
