### ISSUE TITLE
Update text in welcome pane

### ISSUE THREAD

**Issue by aleifer** [PrincetonUniversity/neuron-graph#91]
**Problem**

1. We need to update the text in the welcome box to fix some issues, including the author order and title.
2. Add some contact info for LSI/PNI developers from "Contact Us"
3. Make hyperlinks that open in new tabs for various links

**Current behavior**

1. <img width="400" alt="5CBB3A8C-2C42-45D6-A1CD-1669264CBA16" src="https://user-images.githubusercontent.com/153651/179631705-a6ba56cd-d35d-4429-b298-911c43d259d9.png">
2. Info only on the "Contact Us" pane.
3. No hyperlinks

**Expected behavior**

Update text and hyperlinks to match this Google Doc: https://docs.google.com/document/d/1mFf4RLW8QvE5DItCLo04klDnfJ2LQC_i6RUzVpOFwVs/edit?usp=sharing

1. Should be: Randi, Sharma, Dvali  and Leifer, “Direct measurement of functional connectivity in C. elegans reveals contributions from extrasynaptic signaling.”
2. Consolidate all info that single pane
3. Hyperlinks function and open in new tab (`target="_blank"`)

**Comment by lparsons** [comment]
@bdsinger Updated this issue. Will link to a Google doc shortly that will contain the correct text, hyperlinks, etc.

**Comment by bdsinger** [comment]
I see there is more to it now, so can add those changes to the PR before it is final or closes the issue

**Comment by bdsinger** [comment]
should match now but could use a second (or more) set of eyes (functionality can only be tested by checking out the branch corresp. to the PR and build/running which isn't trivial.)  Screenshot is on the PR page but copying here as well if that is not too annoying to do ..
<img width="651" alt="Screenshot 2022-07-26 at 4 42 20 PM" src="https://user-images.githubusercontent.com/889603/181109031-e0f2db38-eca9-4ee8-ab3c-8b5b8ac67d10.png">
.
