### ISSUE TITLE
Update paper citation to point to arXiv

### ISSUE THREAD

**Issue by lparsons** [PrincetonUniversity/neuron-graph#98]
The paper has been submitted to arXiv. We should use the citation to arXiv until a peer reviewed version is available.

The citation is:

Francesco Randi, Anuj K. Sharma, Sophie Dvali, Andrew M. Leifer, "A functional connectivity atlas of C. elegans measured by neural activation." [arXiv](https://doi.org/10.48550/arXiv.2208.04790), (2022) [[PDF](https://arxiv.org/pdf/2208.04790)]

The URL to the HTML arxiv page is: [https://doi.org/10.48550/arXiv.2208.04790](https://doi.org/10.48550/arXiv.2208.04790)
And the direct to PDF is [https://arxiv.org/pdf/2208.04790](https://arxiv.org/pdf/2208.04790)

* [x] README.md
* [x] Welcome pane "forthcoming manuscript"

**Comment by bdsinger** [comment]
Here's what I have. Did we want full authors names in welcome pane? I left it in last-name format in the welcome pane but full author names in the Readme. Can change no prob
<img width="759" alt="Screen Shot 2022-08-10 at 3 49 40 PM" src="https://user-images.githubusercontent.com/889603/184007323-a0972c88-5904-4e4c-b8a8-fdebf46f4974.png">
<img width="598" alt="Screen Shot 2022-08-10 at 3 50 15 PM" src="https://user-images.githubusercontent.com/889603/184007335-2afbcb23-0864-4593-bb70-c27766256744.png">
.

**Comment by aleifer** [comment]
Looks good to me.

From: Ben Singer ***@***.***>
Date: Wednesday, August 10, 2022 at 12:52 PM
To: PrincetonUniversity/neuron-graph ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [PrincetonUniversity/neuron-graph] Update paper citation to point to arXiv (Issue #98)

Here's what I have. Did we want full authors names in welcome pane? I left it in last-name format in the welcome pane but full author names in the Readme. Can change no prob
[Screen Shot 2022-08-10 at 3 49 40 PM]<https://user-images.githubusercontent.com/889603/184007323-a0972c88-5904-4e4c-b8a8-fdebf46f4974.png>
[Screen Shot 2022-08-10 at 3 50 15 PM]<https://user-images.githubusercontent.com/889603/184007335-2afbcb23-0864-4593-bb70-c27766256744.png>
.

**Comment by bdsinger** [comment]
great, making the PR now
